CF_API: https://api.sys.dev.gsdcf.manulife.com
CF_USER: "barrdal"
CF_PASSWORD: "Manulife123"
CF_ORG: POC
CF_SPACE: barrdal

GITLAB_BRANCH:
GITLAB_SSH_URI: git@10.234.24.84:microservices/ZuulProxy.git
GITLAB_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAuvsc97an0k8bLSeUzkJoNxsG9UMWWoVSENLpSuyqciATD5Gj
    5UGzrsMvmwqCaOlyyz6JGPkDJa5EeUtp87Dltjxa035K8udK+wB0AkWy/LxC2sAJ
    UjJ56inFlsEhMKu4faKtjs+jably/jKeZupLWiD/FUDKmj0CWHeKyQCsHCRLUkGL
    9B551ZyjPZUT1+OtpTvjRSVetRv02MROtJFxVvLNziZjqdH6BvfBpSOd+cf5j93E
    l8w0gQh9gjMwROuxKL7i5ao59V6hY1pwFvyJ3P15FykZKxJ578xyCJUH4RXp4foH
    QkqzLHtJ6EUHtMh8K4XArrCTCefNGxSvfbt8zQIDAQABAoIBAHGN+ayzAD6oDjAh
    Hq0ZBWOaBWLEKHo3B3zyKf53tpfyxMCqyWd8vFwBbBLzkfmW9UFbrDU/XVrv9+PW
    GfWGVCuVge95fpkAQLgpMUsD+0ykJNHm2IJT51h/n+ELT1XYpAWg21ik33Bg0OZx
    5WNJHRQSf/fvTlvXe2owx1eFEgFQOu41reJcBfENt/J968ezo9jWvLyz1toEHG1N
    sbWDp4UkPx+pdvLnD3Lr1qdl57GSvpOMdgh0b5qcwXuWyUdG/HtKTJQOk2Mrp4fH
    Lhp8PMBXlmACERaBIvXOo05WGtAVzhzGOthmuSBYyN5UzU424QaIfZVBhRDCTBLV
    BgkEPwECgYEA7BwVEduN3cqem5914KFpBfTcp5CG4KF4uSAQ/42pZhBEJGkSCnEB
    q98V+KopQu6gKRmfLG+Qk7Cde4iUSVjks883udGOEAt+qyfQqlQK9fpUwvlHj6HF
    ZVQqoiwoBbaixGGr253fixYfvpOipsGZLr7Rh9/9xyBm16UOpOQAvo0CgYEAyruG
    QrdYhunP0oA4aWei3Ub8gt3JYKNs2rR5TIUbbddkEW7aMwa/ODquTLZvWmW1dXXH
    +mZqGv1ZgXE1ilHwzQFJ7b2245gaxYOKMqG1E6dAO1hnJgeV5OiZl1SSqrcTNkJe
    kxPeXPiFJsdGIHteSWH3Nd6flqjpSXSnKEv6R0ECgYEA2UKp/Kmr7EezFP5xiIbe
    ThXYKPRruC29GZQxMAaZtwoGuf5ZFHSSFiYMYKmrmCReChPCjTAHuG8PKoot8SQ0
    JmTqITl74LXDFBlqACGfiGKWNmcNe1RfgHMnW90H4uIA+nXpnwexmJl+Em5lf86r
    dwEtazsomV/uYkZGqGIJcU0CgYBl+JS7kgURNyG1O5EkU2Bz9HSmTnAwD4N9LjGk
    736wbRqEOkG+ULJ10e5B37F6wpXXEvsXU9Qi5zPSC+NmQ3jfZLqOvlHzgFpW5qbo
    eLXfwMxqDTk0w7P9g5FdsMhk3djn/dIcIG5ETSyMKMd5JxRxzLjPe77BxQwySl6Z
    wj2NAQKBgQDaBAwbmSqvR2/nnNr5iPThu1Pyw4iMyC4XmxGcYiUWhYATvSXd2kWu
    eiom0Vpc/xD/W9eQe0pp5GnNS2CqWBP9Gpxtg1mTRmGNvqi0V2L1mkmqAgzhhkIX
    nvFZnQA7bWZSmc2hAW8dkl4OUzM/SM5QPJNHxoL1w5EXv0cmlCbiKg==
    -----END RSA PRIVATE KEY-----